blog/urls.py
from django.urls import path
from .views import render_posts, post_detail

app_name= "blog"

urlpatterns = [
    path('', render_posts, name='posts'),
    path("<int:post_id>", post_detail, name="post_detail")
]

django_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from portfolio import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('blog/', include('blog.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
import datetime
from cloudinary.models import CloudinaryField

class Post (models.Model):
    title=models.CharField(max_length=100)
    description = models.TextField()
    image = CloudinaryField('image')
    date = models.DateField(datetime.date.today)

# Create your models here.

portfolio/models.py
from django.db import models
from django.db.models.fields import CharField, URLField
from cloudinary.models import CloudinaryField

class Project(models.Model):
    title = CharField(max_length=100)
    description = CharField(max_length=250)
    image = CloudinaryField('image')
    url = URLField(blank=True)

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post
def render_posts(request):
    articulos = Post.objects.all()
    return render(request,'posts.html',{'posts':articulos})

def post_detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    return render(request,'post_detail.html', {"post": post})

portfolio/views.py
from django.shortcuts import render
from .models import Project

# Create your views here.
def home(request):
    projects = Project.objects.all()
    return render(request,'home.html', {'projects': projects})

blog/templates/post_detail.html
{% extends 'layout.html'%}
{% block content %}

<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Cuadro de Texto Formateado</title>
    <style>
        .text-box {
            border: 1px solid #000;
            padding: 10px;
            white-space: pre-wrap; 
            font-family: Arial, sans-serif; 
        }
    </style>
</head>

<div class="text-center">
    <h2>{{post.title}}</h2>
    <h3 class="my-2 h5 text-muted">{{post.date|date:'F jS Y'}}</h3>
        </div>
            
                <img src="{{post.image.url}}" alt="{{post.title}}" class="img-fluid" style="display: block; margin: 0 auto;" >
            
        
        <div class="text-box">
        <p>{{post.description|safe}}</p>
    </div>



{% endblock %}

blog/templates/posts.html
{% extends 'layout.html'%}
{% block content %}

<h1>Personajes</h1>

{% for post in posts %}

<div class="p-3">
    <div class="card card-body bg-black">
        <div class="row">
    
            <div class="col-3">
                <img src="{{post.image.url}}" alt="{{post.title}}" class="img-fluid">
            </div>
    
            <div class="col-9">
                <h2>{{post.title}}</h2>
                <h3>{{post.date|date:"D d M Y" }}</h3>
                <p>{{post.description|safe|truncatechars:500}}</p>
                <a href="{% url 'blog:post_detail' post.id %}" class="btn btn-primary">Ver Detalles</a>
            </div>
    
        </div>
    
    
    </div>
</div>

{% endfor %}

{% endblock %}

portfolio/templates/home.html
{% extends 'layout.html' %}

{% block content %}

{% load static %}


<header class="row bg-black">

    <div class="col-md-4">
        <img src="{% static 'portfolio/got.jpg'  %}" style="width: 300px; height: auto;">
    </div>

    <div class="col-md-8 my-auto">
        <h1>La <strong> Casa del Dragon</strong></h1>
        <h3>La lucha por el trono de hierro</h3>
        <p>La Casa del Dragón, precuela de Juego de Tronos, se sitúa 200 años antes de los eventos de la serie original y 
            narra la historia del origen de la Casa Targaryen y la Danza de Dragones, una guerra civil que enfrentó a dos 
            bandos de la familia por el control del Trono de Hierro.
            La trama principal gira en torno a la princesa Rhaenyra Targaryen, hija del rey Viserys I, quien es nombrada
            heredera al trono. Sin embargo, su nombramiento genera tensiones con su tío Daemon Targaryen, hermano del rey y 
            ambicioso guerrero que también desea el trono.
            La serie explora temas como el poder, la ambición, la traición y la familia, a través de la compleja red de 
            relaciones entre los personajes. También se adentra en la historia y la cultura de los Targaryen, incluyendo sus 
            tradiciones, costumbres y, por supuesto, sus dragones.
            </p>
        <a href="{% static 'portfolio/practica.pdf' %}" 
        class="btn btn-primary btn-lg rounded-0 my-3"
        >Download CV</a>
    </div>
</header>


<div class="row my-4 text-center">

<h3>Ayuda Audiovisual</h3>
<p>Estos son videos que ayudaran a comprender mejor la trama de esta increible historia</p>

    {% for project in projects %}
    
    <div class="col-md-4 p-4">
        <div class="card bg-black card-project">
            <img src="{{project.image.url}}" alt="{{project.title}}" class="card-img-top">
            <div class="card-body">
                <h2>{{project.title}}</h2>
                <p>{{project.description}}</p>
                
                {% if project.url %}
                <a href="{{project.url}}" class="btn btn-light rounded-0 btn-sm" target="_blank">{{project.url}}</a>
                {% endif %}
            </div>
        </div>
    </div>
    
    {% endfor %}

    {% endblock %}

</div>

portfolio/templates/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Django Portfolio</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" 
    integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" 
    crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'main.css' %}">
</head>
</head>
<body class="text-light">
    
    {% include 'partials/navbar.html'%}

    <div class="container p-4">

        {% block content %}
        {% endblock %}

    </div>
</body>
</html>

portfolio/templates/partials/navbar.html
{% load static %}

<nav class="navbar navbar-expand-lg navbar-dark bg-black">
    <div class="container-fluid">
      <a class="navbar-brand fw-bold fst-italic" href="/">LA CASA DEL DRAGON</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ms-auto">
          <li class="nav-item">
            <a class="nav-link" href="/blog">Blog</a>
          </li>
          <li class="nav-item d-flex align-items-center">
            <a class="btn btn-primary btn-sm" href="{% static 'portfolio/practica.pdf' %}" target="_blank">Download CV</a>
          </li>
            </ul>
          </li>
        </ul>
      </div>
    </div>
  </nav>